(module
  (memory (export "memory") 1 1600)
  (global $state (mut i32) (i32.const 1))
  (func $random (result f32)
    (global.set $state (i32.xor (global.get $state) (i32.shl (global.get $state) (i32.const 13))))
    (global.set $state (i32.xor (global.get $state) (i32.shr_u (global.get $state) (i32.const 17))))
    (global.set $state (i32.xor (global.get $state) (i32.shl (global.get $state) (i32.const 5))))
    (f32.div (f32.convert_i32_u (i32.shr_u (global.get $state) (i32.const 8))) (f32.const 16777216)))
  ;; Interleaved position/radius, velocity/inverse mass, angular velocity/pad.
  ;; Grid separation uses the maximum radius, so every seed is non-overlapping.
  (func (export "seed") (param $count i32) (param $nx i32) (param $nz i32)
    (param $width f32) (param $height f32) (param $depth f32)
    (param $radius f32) (param $variation f32) (param $mass f32)
    (param $spacing f32) (param $seed i32)
    (local $i i32) (local $p i32) (local $r f32) (local $scale f32) (local $x f32) (local $z f32)
    (global.set $state (i32.or (local.get $seed) (i32.const 1)))
    (local.set $i (i32.const 0))
    (block $done (loop $loop
      (br_if $done (i32.ge_u (local.get $i) (local.get $count)))
      (local.set $p (i32.mul (local.get $i) (i32.const 48)))
      (local.set $scale (f32.add (f32.const 1) (f32.mul (f32.mul (local.get $variation) (f32.const 4)) (call $random))))
      (local.set $r (f32.mul (local.get $radius) (local.get $scale)))
      (local.set $x (f32.mul (f32.sub (f32.add (f32.convert_i32_u (i32.rem_u (local.get $i) (local.get $nx))) (f32.const 0.5)) (f32.mul (f32.convert_i32_u (local.get $nx)) (f32.const 0.5))) (local.get $spacing)))
      (local.set $z (f32.mul (f32.sub (f32.add (f32.convert_i32_u (i32.rem_u (i32.div_u (local.get $i) (local.get $nx)) (local.get $nz))) (f32.const 0.5)) (f32.mul (f32.convert_i32_u (local.get $nz)) (f32.const 0.5))) (local.get $spacing)))
      (f32.store (local.get $p) (local.get $x))
      (f32.store offset=4 (local.get $p) (f32.sub (local.get $height) (f32.mul (f32.add (f32.convert_i32_u (i32.div_u (local.get $i) (i32.mul (local.get $nx) (local.get $nz)))) (f32.const 0.5)) (local.get $spacing))))
      (f32.store offset=8 (local.get $p) (local.get $z))
      (f32.store offset=12 (local.get $p) (local.get $r))
      (f32.store offset=16 (local.get $p) (f32.mul (f32.sub (call $random) (f32.const 0.5)) (f32.const 0.03)))
      (f32.store offset=20 (local.get $p) (f32.const 0))
      (f32.store offset=24 (local.get $p) (f32.mul (f32.sub (call $random) (f32.const 0.5)) (f32.const 0.03)))
      (f32.store offset=28 (local.get $p) (f32.div (f32.const 1) (f32.mul (local.get $mass) (f32.mul (local.get $scale) (f32.mul (local.get $scale) (local.get $scale))))))
      (f32.store offset=32 (local.get $p) (f32.const 0))
      (f32.store offset=36 (local.get $p) (f32.const 0))
      (f32.store offset=40 (local.get $p) (f32.const 0))
      (f32.store offset=44 (local.get $p) (f32.const 0))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $loop)))))
